BEGIN TRANSACTION;

INSERT INTO users (username,password_hash,role,first_time, first_name, last_name, email) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER', false, 'user', 'default', 'user@gmail.com');
INSERT INTO users (username,password_hash,role,first_time, first_name, last_name, email) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN', false, 'admin', 'default', 'admin@gmail.com');

INSERT INTO user_status (status) VALUES ('Pending');
INSERT INTO user_status (status) VALUES ('Approved');
INSERT INTO user_status (status) VALUES ('Rejected');

INSERT INTO adoption_status (status) VALUES ('Avaliable');
INSERT INTO adoption_status (status) VALUES ('Unavaliable');

INSERT INTO pets (name, gender, weight, species, breed, color, birthday, description, status) VALUES ('Miso', 'Female', 13, 'Cat', 'Domestic Shorthair', 'Black', '2024-09-03', 'Miso has no sense of loyalty. Will sleep in any bed regardless if you water and pet her. Likes: Water & Pets. Dislikes: Food. So cute you will forgive her ultimately when the little heart pops up over her head and she meows.', 1);
INSERT INTO pets (name, gender, weight, species, breed, color, birthday, description, status) VALUES ('Figgy', 'Male', 50, 'Dog', 'German Shepard Mix', 'White', '2018-06-15', 'Figgy enjoys his toy monkey, watching the birds in the backyard, and going on nightly neighborhood patrols. He dislikes the wind, rain, and USPS.', 1);
INSERT INTO pets (name, gender, weight, species, breed, color, birthday, description, status) VALUES ('PuPu', 'Male', 45, 'Dog', 'Husky', 'Black and White', '2022-12-03', 'PuPu is full of energy and loves to run, jump, and have fun with other dogs. He’s super friendly but gets a bit uneasy around large groups of kids or strangers, especially men.', 1);
INSERT INTO pets (name, gender, weight, species, breed, color, birthday, description, status) VALUES ('Ellie', 'Female', 15, 'Cat', 'Maine Coon Mix', 'Black', '2022-05-04', 'The truest sour patch cat, Ellie is full of personality and surprises. One moment she might give you a playful bite for petting her just a bit too enthusiastically, and the next, she’s curling up beside you for a cozy snuggle. A true feline adventurer, she enjoys chasing after her fellow cats, but her greatest nemesis? The dreaded vacuum! With her moody charm and unpredictable antics, Ellie is a delightful whirlwind of affection and attitude.', 1);
INSERT INTO pets (name, gender, weight, species, breed, color, birthday, description, status) VALUES ('Osiris', 'Male', 12, 'Cat', 'Domestic Longhair', 'Black', '2017-03-12', 'The ultimate scaredy cat. Not deserving of his name that should impose fear on mortals. Acts very dog-like and knows how to sit, lay down, shake, high five, and fetch. Loves salmon. Not the sharpest crayon in the box but makes up for it by being super snuggly and he does not eat plants, chew cords, spray, and he’s typically very quiet.', 1);
INSERT INTO pets (name, gender, weight, species, breed, color, birthday, description, status) VALUES ('Cypress', 'Male', 13, 'Cat', 'Domestic Shorthair', 'Grey and White Tabby', '2020-05-01', 'A true foodie at heart, Cypress is always on a quest to explore the world—one bite at a time. His adventurous spirit leads him to taste everything in sight, which spells trouble for any plant that crosses his path (many have met their untimely demise!). With a penchant for snuggles and the loudest purrs, he’s a lovable companion who knows how to charm. But beware: this little mischief-maker has a knack for wreaking havoc, especially on carpets! Cypress is a delightful blend of curiosity and cuddles, always ready to make you smile.', 1);
INSERT INTO pets (name, gender, weight, species, breed, color, birthday, description, status) VALUES ('Maris', 'Female', 7, 'Cat', 'Domestic Shorthair', 'Black', '2020-05-15', 'The quintessential "cat liquid," Maris weighs in at just over 7 pounds. She’s aware that the world can be bigger and scarier than she is, but her bravery shines through once she acclimates to her surroundings. When she feels safe, this affectionate feline loves nothing more than curling up on her favorite human’s lap, showering them with playful face licks, and enjoying spirited playtime with her beloved brother, Cypress. Maris is a gentle soul with a heart full of warmth and playfulness.', 1);
INSERT INTO pets (name, gender, weight, species, breed, color, birthday, description, status) VALUES ('Nora', 'Female', 14, 'Cat', 'Domestic Longhair', 'Black and White', '2014-07-18', 'Nora might be a little old, but she has lots of energy in her. Raised as an indoor cat in a house with two dogs, Nora sees herself as a member of the pack. She’s not very good at jumping, but she’ll use her jumping skills to get into your lap and steal all your attention. Warning: addicted to catnip!', 1);
INSERT INTO pets (name, gender, weight, species, breed, color, birthday, description, status) VALUES ('Zuko', 'Male', 40, 'Dog', 'Pitbull', 'Brown and White', '2016-03-22', 'Zuko is ADHD given dog form. At barely shin height he can jump high enough to lick the nose of most people. He’s very protective of his family when it comes to new people, unless the people he cares about introduce him, at which point he switches to being an attention hog. He lost his eye in an accident when he was 3, but that has not stopped him from living his fullest and happiest life!', 1);
INSERT INTO pets (name, gender, weight, species, breed, color, birthday, description, status) VALUES ('Bean', 'Female', 35, 'Dog', 'Labrador Retriever Mix', 'Golden', '2022-02-14', 'Bean is a very proper little lady. She loves sitting in front of the fire, over a heat vent, or in front of the oven if it’s on. She can be a little skittish, but give her treats and she’ll love you forever. She loves to chase chipmunks, deer, and snakes, but she always comes back!', 1);
INSERT INTO pets (name, gender, weight, species, breed, color, birthday, description, status) VALUES ('Raindrop', 'Female', 14, 'Cat', 'Domestic Shorthair', 'Black', '2016-03-22', 'A playful spirit with a love for adventure, Raindrop spends her days chasing elusive lights and enjoying long, cozy naps. Always ready to chat, she has plenty to say to her humans, adding a delightful touch of personality to the household.', 1);
INSERT INTO pets (name, gender, weight, species, breed, color, birthday, description, status) VALUES ('Brody', 'Male', 80, 'Dog', 'Great Pyrenees', 'White', '2021-09-23', 'Brody is a 3-year-old Great Pyrenees with a strong-willed and independent personality, yet he has a calm and gentle nature that makes him a perfect companion. Known for his occasional stubbornness, Brody enjoys doing things on his own terms, but his love for outdoor adventures always shines through. He thrives on hikes, where he can explore new scents and scenery, and he’s surprisingly comfortable on the water, enjoying paddle boarding trips. At home, Brody is mellow and laid-back, often lounging in front of a fan or keeping watch over his surroundings, but he’s always eager to join in on the next adventure.', 1);
INSERT INTO pets (name, gender, weight, species, breed, color, birthday, description, status) VALUES ('Teddy', 'Male', 20, 'Dog', 'Great Pyrenees', 'White', '2024-08-05', 'Teddy is a playful, energetic Great Pyrenees and Alaskan Malamute mix, just a few weeks old and full of curiosity. As the newest member of the family, he’s still learning the ropes, especially when it comes to potty training. His boundless energy keeps him constantly on the move, much to the annoyance of his big brother, Brody, who has to put up with Teddy’s playful antics. Despite being a bit of a handful, Teddy’s lively spirit and eagerness to explore make him an exciting, if mischievous, addition to the household.', 1);
INSERT INTO pets (name, gender, weight, species, breed, color, birthday, description, status) VALUES ('Zana', 'Female', 13, 'Cat', 'Domestic Shorthair', 'Tabby', '2020-05-01', 'A gentle soul with a cautious heart, Zana is initially terrified of new people. However, once she warms up to you, her affectionate side shines through as she lovingly makes biscuits on your lap. A true connoisseur of comfort, she seeks out warm spots for her naps, cherishing those cozy moments.', 1);
INSERT INTO pets (name, gender, weight, species, breed, color, birthday, description, status) VALUES ('Lando', 'Male', 20, 'Dog', 'Scottish Terrier', 'Black', '2019-06-22', 'Lando is independent, NOT a cuddler, but very protective of his family. He’s 5 years old. Enjoys lazy days, does not like walks over one mile.', 1);
INSERT INTO pets (name, gender, weight, species, breed, color, birthday, description, status) VALUES ('Minerva', 'Female', 12, 'Cat', 'Domestic Shorthair', 'Cream', '2015-07-12', 'Minerva is chill as hell and likes pets of all kinds, and loves to be held or cuddled. She’s a bit bossy when it comes to food though. Food of any kind.', 1);
INSERT INTO pets (name, gender, weight, species, breed, color, birthday, description, status) VALUES ('Jenkins', 'Male', 14, 'Cat', 'Domestic Shorthair', 'Black and White', '2018-05-12', 'The epitome of a laid-back tom cat, Jenkins is a lover of all and a true chill master. Fearless and friendly, he embraces everyone with open paws! His favorite toys? Stuffed fish, of course! But when the clock strikes 3 AM, watch out—Jenkins has a quirky habit of eerily screaming into the void, adding a touch of mystery to his otherwise relaxed demeanor.', 1);
INSERT INTO pets (name, gender, weight, species, breed, color, birthday, description, status) VALUES ('Alfred', 'Male', 16, 'Cat', 'Domestic Shorthair', 'Grey', '2019-10-31', 'Alfred is timid, flighty and anxious, but a really sweet guy when you get to know him. He’s rambunctious and filled with energy, and loves to play.', 1);
INSERT INTO pets (name, gender, weight, species, breed, color, birthday, description, status) VALUES ('Fergus', 'Male', 50, 'Dog', 'Labradoodle', 'Brown', '2021-10-09', 'This playful pup is all about the fun! He loves toys, treats, and especially enjoys a lively game of keep away. While he has a heart full of energy and joy, Fergus is not a fan of cameras and screens—he prefers to stay in the moment and enjoy life without the spotlight. With his playful antics and charming personality, Fergus is sure to keep you entertained and smiling!', 1);

COMMIT TRANSACTION;

